server:
  port: 8080

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: signingkey
  encoding-strength: 256
  security-realm: vocab realmushka
  jwt:
    client-id: clientid
    client-secret: secret
    scope-read: read
    scope-write: write
    resource-ids: testjwtresourceid
    access_token_validity_in_seconds: 99999999
    refresh_token_validity_in_seconds: 2592000 #one month

spring:
  data:
    mongodb:
      uri: mongodb://root:testpassword@127.0.0.1:27017/vocab?authSource=admin

logging:
  level:
    root: info
    com.abadeksvp.vocabbackend.service: debug
    com.abadeksvp.vocabbackend.security: debug