version: '2'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: vocab
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testpassword
    ports:
      - '27017:27017'
    volumes:
      - ./mongodbdata:/data/db
    networks:
      - vocab-network
#
#  vocab:
#    image: vocab:1.0.0
#    restart: always
#    ports:
#      - "8090:8080"
#    environment:
#      - SERVER_PORT=8080
#      - DATABASE_URI=mongodb://root:testpassword@mongo:27017/vocab?authSource=admin
#    depends_on:
#      - mongo
#    networks:
#      - vocab-network

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - mongo
    networks:
      - vocab-network

networks:
  vocab-network:
    driver: bridge